. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/config
. ~/bin/dotfiles/bash/aliases

export LC_ALL=en_US.UTF-8
export SYBASE=/usr/local

# to use the fink hierarchy if installed
test -r /sw/bin/init.sh && . /sw/bin/init.sh

if [[ -s /Users/roy/.rvm/scripts/rvm ]] ; then source /Users/roy/.rvm/scripts/rvm ; fi

#ff(){
#  open -a /Applications/Firefox.app/ "$1"
#}
