#!/usr/bin/ruby -w

require "rubygems"
require 'benchmark'
require "progressbar"

if ARGV[0] && ARGV[1]
  site = ARGV.first
  how_many = ARGV[1].to_i
else
  puts "usage: perftest google.com 10"
  exit
end

pbar = ProgressBar.new("Benchmarking #{site}", how_many)
realtime = Benchmark.realtime do
  how_many.times do |x|
    pbar.inc
    system("curl -o /dev/null -s #{site}")
  end
end

pbar.finish

msg = "processed in %.4f seconds avg: %.4f" % [realtime, realtime / how_many]
puts msg
